name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '22'

      - name: Cache pnpm modules
        uses: actions/cache@v4.0.2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: true

      - run: pnpm i
      - run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: page
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: page
          path: .
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .
      - name: Deploy
        uses: actions/deploy-pages@v4.0.4
